### ISSUE TITLE
picker position...

### ISSUE THREAD

**Issue by Mark-Mark** [joshsalverda/datepickr#16]
Hello,

I am fairly new to Javascript/CSS/HTML. I have been a programmer for decades. The position of the picker is the question. I found, in the CSS, where the position is defined and I can change it.

The issue is I want the picker to appear next to the input field; there are several date input fields on the page. The CSS is global and I have not discovered how to position the picker based on the input element position. 

The ID of the picker is what is vexing me. I assume if I had the picker ID, I could add code to position the picker.

Ideas?

Thanks,

Mark
P.S. Thank you for publishing this date picker.

**Comment by joshsalverda** [comment]
Hi, sorry for the delay getting back to you, I've been super busy lately. You should be able to update the datepickr.css file on lines 18 and 19 to use `top: 0;` and `left: 100%;` if you want all the date pickers to show up at the top right of your input fields. Hopefully that solves your issue, unless I am totally wrong about what you are asking :laughing: 

The id of the element shouldn't matter, because the date picker code wraps each element in a container div with a class name of datepickr-wrapper. This wrapper div has position relative on it which causes the absolutely positioned calendar div to be positioned relative to it. You can read more about relative and absolute positioning here: https://developer.mozilla.org/en-US/docs/Web/CSS/position

**Comment by Mark-Mark** [comment]
Thanks for the response.

Yeah, it does not answer the question. All the pickers appear at the CSS location and not next to the input field.
